import sys
import os

def main():
  args = sys.argv

  count_id = 100

  files = os.listdir('./OPT')
  for i, filename in enumerate(files):
    if 'parse_option.py' in filename:
      continue
    with open('./OPT/' + filename) as f:
      lines = f.readlines()
      for j, line in enumerate(lines):
        if line == "\n":
          continue
        # print(j, line, end='')
        option_name = get_option_group_name(line)
        option_rate = get_option_rate(line)
        option_value = get_option_value(line)
        if option_name:
          print(option_name)
        if option_rate:
          print(option_rate)
        if option_value:
          print(option_value)


def get_option_group_name(line):
  if '(' in line:
    return line.split(':')[0]


def get_option_rate(line):
  if 'Rate' in line:
    return line.split('Rate: ')[1].replace('\n', '')


def get_option_value(line):
  list_option_name = [
    'VAR_MAXHPAMOUNT',
    'VAR_MAXSPAMOUNT',
    'VAR_STRAMOUNT',
    'VAR_AGIAMOUNT',
    'VAR_VITAMOUNT',
    'VAR_INTAMOUNT',
    'VAR_DEXAMOUNT',
    'VAR_LUKAMOUNT',
    'VAR_MAXHPPERCENT',
    'VAR_MAXSPPERCENT',
    'VAR_HPACCELERATION',
    'VAR_SPACCELERATION',
    'VAR_ATKPERCENT',
    'VAR_MAGICATKPERCENT',
    'VAR_PLUSASPD',
    'VAR_PLUSASPDPERCENT',
    'VAR_ATTPOWER',
    'VAR_HITSUCCESSVALUE',
    'VAR_ATTMPOWER',
    'VAR_ITEMDEFPOWER',
    'VAR_MDEFPOWER',
    'VAR_AVOIDSUCCESSVALUE',
    'VAR_PLUSAVOIDSUCCESSVALUE',
    'VAR_CRITICALSUCCESSVALUE',
    'ATTR_TOLERACE_NOTHING',
    'ATTR_TOLERACE_WATER',
    'ATTR_TOLERACE_GROUND',
    'ATTR_TOLERACE_FIRE',
    'ATTR_TOLERACE_WIND',
    'ATTR_TOLERACE_POISON',
    'ATTR_TOLERACE_SAINT',
    'ATTR_TOLERACE_DARKNESS',
    'ATTR_TOLERACE_TELEKINESIS',
    'ATTR_TOLERACE_UNDEAD',
    'ATTR_TOLERACE_ALLBUTNOTHING',
    'DAMAGE_PROPERTY_NOTHING_USER',
    'DAMAGE_PROPERTY_NOTHING_TARGET',
    'DAMAGE_PROPERTY_WATER_USER',
    'DAMAGE_PROPERTY_WATER_TARGET',
    'DAMAGE_PROPERTY_GROUND_USER',
    'DAMAGE_PROPERTY_GROUND_TARGET',
    'DAMAGE_PROPERTY_FIRE_USER',
    'DAMAGE_PROPERTY_FIRE_TARGET',
    'DAMAGE_PROPERTY_WIND_USER',
    'DAMAGE_PROPERTY_WIND_TARGET',
    'DAMAGE_PROPERTY_POISON_USER',
    'DAMAGE_PROPERTY_POISON_TARGET',
    'DAMAGE_PROPERTY_SAINT_USER',
    'DAMAGE_PROPERTY_SAINT_TARGET',
    'DAMAGE_PROPERTY_DARKNESS_USER',
    'DAMAGE_PROPERTY_DARKNESS_TARGET',
    'DAMAGE_PROPERTY_TELEKINESIS_USER',
    'DAMAGE_PROPERTY_TELEKINESIS_TARGET',
    'DAMAGE_PROPERTY_UNDEAD_USER',
    'DAMAGE_PROPERTY_UNDEAD_TARGET',
    'MDAMAGE_PROPERTY_NOTHING_USER',
    'MDAMAGE_PROPERTY_NOTHING_TARGET',
    'MDAMAGE_PROPERTY_WATER_USER',
    'MDAMAGE_PROPERTY_WATER_TARGET',
    'MDAMAGE_PROPERTY_GROUND_USER',
    'MDAMAGE_PROPERTY_GROUND_TARGET',
    'MDAMAGE_PROPERTY_FIRE_USER',
    'MDAMAGE_PROPERTY_FIRE_TARGET',
    'MDAMAGE_PROPERTY_WIND_USER',
    'MDAMAGE_PROPERTY_WIND_TARGET',
    'MDAMAGE_PROPERTY_POISON_USER',
    'MDAMAGE_PROPERTY_POISON_TARGET',
    'MDAMAGE_PROPERTY_SAINT_USER',
    'MDAMAGE_PROPERTY_SAINT_TARGET',
    'MDAMAGE_PROPERTY_DARKNESS_USER',
    'MDAMAGE_PROPERTY_DARKNESS_TARGET',
    'MDAMAGE_PROPERTY_TELEKINESIS_USER',
    'MDAMAGE_PROPERTY_TELEKINESIS_TARGET',
    'MDAMAGE_PROPERTY_UNDEAD_USER',
    'MDAMAGE_PROPERTY_UNDEAD_TARGET',
    'BODY_ATTR_NOTHING',
    'BODY_ATTR_WATER',
    'BODY_ATTR_GROUND',
    'BODY_ATTR_FIRE',
    'BODY_ATTR_WIND',
    'BODY_ATTR_POISON',
    'BODY_ATTR_SAINT',
    'BODY_ATTR_DARKNESS',
    'BODY_ATTR_TELEKINESIS',
    'BODY_ATTR_UNDEAD',
    'RACE_TOLERACE_NOTHING',
    'RACE_TOLERACE_UNDEAD',
    'RACE_TOLERACE_ANIMAL',
    'RACE_TOLERACE_PLANT',
    'RACE_TOLERACE_INSECT',
    'RACE_TOLERACE_FISHS',
    'RACE_TOLERACE_DEVIL',
    'RACE_TOLERACE_HUMAN',
    'RACE_TOLERACE_ANGEL',
    'RACE_TOLERACE_DRAGON',
    'RACE_DAMAGE_NOTHING',
    'RACE_DAMAGE_UNDEAD',
    'RACE_DAMAGE_ANIMAL',
    'RACE_DAMAGE_PLANT',
    'RACE_DAMAGE_INSECT',
    'RACE_DAMAGE_FISHS',
    'RACE_DAMAGE_DEVIL',
    'RACE_DAMAGE_HUMAN',
    'RACE_DAMAGE_ANGEL',
    'RACE_DAMAGE_DRAGON',
    'RACE_MDAMAGE_NOTHING',
    'RACE_MDAMAGE_UNDEAD',
    'RACE_MDAMAGE_ANIMAL',
    'RACE_MDAMAGE_PLANT',
    'RACE_MDAMAGE_INSECT',
    'RACE_MDAMAGE_FISHS',
    'RACE_MDAMAGE_DEVIL',
    'RACE_MDAMAGE_HUMAN',
    'RACE_MDAMAGE_ANGEL',
    'RACE_MDAMAGE_DRAGON',
    'RACE_CRI_PERCENT_NOTHING',
    'RACE_CRI_PERCENT_UNDEAD',
    'RACE_CRI_PERCENT_ANIMAL',
    'RACE_CRI_PERCENT_PLANT',
    'RACE_CRI_PERCENT_INSECT',
    'RACE_CRI_PERCENT_FISHS',
    'RACE_CRI_PERCENT_DEVIL',
    'RACE_CRI_PERCENT_HUMAN',
    'RACE_CRI_PERCENT_ANGEL',
    'RACE_CRI_PERCENT_DRAGON',
    'RACE_IGNORE_DEF_PERCENT_NOTHING',
    'RACE_IGNORE_DEF_PERCENT_UNDEAD',
    'RACE_IGNORE_DEF_PERCENT_ANIMAL',
    'RACE_IGNORE_DEF_PERCENT_PLANT',
    'RACE_IGNORE_DEF_PERCENT_INSECT',
    'RACE_IGNORE_DEF_PERCENT_FISHS',
    'RACE_IGNORE_DEF_PERCENT_DEVIL',
    'RACE_IGNORE_DEF_PERCENT_HUMAN',
    'RACE_IGNORE_DEF_PERCENT_ANGEL',
    'RACE_IGNORE_DEF_PERCENT_DRAGON',
    'RACE_IGNORE_MDEF_PERCENT_NOTHING',
    'RACE_IGNORE_MDEF_PERCENT_UNDEAD',
    'RACE_IGNORE_MDEF_PERCENT_ANIMAL',
    'RACE_IGNORE_MDEF_PERCENT_PLANT',
    'RACE_IGNORE_MDEF_PERCENT_INSECT',
    'RACE_IGNORE_MDEF_PERCENT_FISHS',
    'RACE_IGNORE_MDEF_PERCENT_DEVIL',
    'RACE_IGNORE_MDEF_PERCENT_HUMAN',
    'RACE_IGNORE_MDEF_PERCENT_ANGEL',
    'RACE_IGNORE_MDEF_PERCENT_DRAGON',
    'CLASS_DAMAGE_NORMAL_TARGET',
    'CLASS_DAMAGE_BOSS_TARGET',
    'CLASS_DAMAGE_NORMAL_USER',
    'CLASS_DAMAGE_BOSS_USER',
    'CLASS_MDAMAGE_NORMAL',
    'CLASS_MDAMAGE_BOSS',
    'CLASS_IGNORE_DEF_PERCENT_NORMAL',
    'CLASS_IGNORE_DEF_PERCENT_BOSS',
    'CLASS_IGNORE_MDEF_PERCENT_NORMAL',
    'CLASS_IGNORE_MDEF_PERCENT_BOSS',
    'DAMAGE_SIZE_SMALL_TARGET',
    'DAMAGE_SIZE_MIDIUM_TARGET',
    'DAMAGE_SIZE_LARGE_TARGET',
    'DAMAGE_SIZE_SMALL_USER',
    'DAMAGE_SIZE_MIDIUM_USER',
    'DAMAGE_SIZE_LARGE_USER',
    'DAMAGE_SIZE_PERFECT',
    'DAMAGE_CRI_TARGET',
    'DAMAGE_CRI_USER',
    'RANGE_ATTACK_DAMAGE_TARGET',
    'RANGE_ATTACK_DAMAGE_USER',
    'HEAL_VALUE',
    'HEAL_MODIFY_PERCENT',
    'DEC_SPELL_CAST_TIME',
    'DEC_SPELL_DELAY_TIME',
    'DEC_SP_CONSUMPTION',
    'WEAPON_ATTR_NOTHING',
    'WEAPON_ATTR_WATER',
    'WEAPON_ATTR_GROUND',
    'WEAPON_ATTR_FIRE',
    'WEAPON_ATTR_WIND',
    'WEAPON_ATTR_POISON',
    'WEAPON_ATTR_SAINT',
    'WEAPON_ATTR_DARKNESS',
    'WEAPON_ATTR_TELEKINESIS',
    'WEAPON_ATTR_UNDEAD',
    'WEAPON_INDESTRUCTIBLE',
    'BODY_INDESTRUCTIBLE',
    'MDAMAGE_SIZE_SMALL_TARGET',
    'MDAMAGE_SIZE_MIDIUM_TARGET',
    'MDAMAGE_SIZE_LARGE_TARGET',
    'MDAMAGE_SIZE_SMALL_USER',
    'MDAMAGE_SIZE_MIDIUM_USER',
    'MDAMAGE_SIZE_LARGE_USER',
    'ATTR_TOLERACE_ALL',
    'RACE_WEAPON_TOLERACE_NOTHING',
    'RACE_WEAPON_TOLERACE_UNDEAD',
    'RACE_WEAPON_TOLERACE_ANIMAL',
    'RACE_WEAPON_TOLERACE_PLANT',
    'RACE_WEAPON_TOLERACE_INSECT',
    'RACE_WEAPON_TOLERACE_FISHS',
    'RACE_WEAPON_TOLERACE_DEVIL',
    'RACE_WEAPON_TOLERACE_HUMAN',
    'RACE_WEAPON_TOLERACE_ANGEL',
    'RACE_WEAPON_TOLERACE_DRAGON',
    'RACE_TOLERACE_PLAYER_HUMAN',
    'RACE_TOLERACE_PLAYER_DORAM',
    'RACE_DAMAGE_PLAYER_HUMAN',
    'RACE_DAMAGE_PLAYER_DORAM',
    'RACE_MDAMAGE_PLAYER_HUMAN',
    'RACE_MDAMAGE_PLAYER_DORAM',
    'RACE_CRI_PERCENT_PLAYER_HUMAN',
    'RACE_CRI_PERCENT_PLAYER_DORAM',
    'RACE_IGNORE_DEF_PERCENT_PLAYER_HUMAN',
    'RACE_IGNORE_DEF_PERCENT_PLAYER_DORAM',
    'RACE_IGNORE_MDEF_PERCENT_PLAYER_HUMAN',
    'RACE_IGNORE_MDEF_PERCENT_PLAYER_DORAM',
    'MELEE_ATTACK_DAMAGE_TARGET',
    'MELEE_ATTACK_DAMAGE_USER',
  ]
  option_name = ''
  min_value = 0
  max_value = 0
  if ': [' in line:
    option_name = line.split(': [')[0].replace('\t', '')
    if option_name not in list_option_name:
      print('Option name not in list option name: ', option_name)
    min_value = line.split(': [')[1].split(', ')[0]
    max_value = line.split(', ')[1].split(']\n')[0]
    return (option_name, min_value, max_value)


if __name__ == "__main__":
  main()